stages:
  - test
  - deploy
test-all:
  stage:test
except:
  - master
  - script:
      -mvn clean install
test-unit:
  stage : test
  only:
    -master
  script:
    -mvn clean package 
    -cp target/TestAndDevOPS*.jar TestAndDevOPS${CI_COMMIT_SHA}.jar
  artifacts:
  name: TestAndDevOPS
  expire_in: 1 week
  paths:
   - TestAndDevOPS${CI_COMMIT_SHA}.jar
deploy:
 stage: deploy
 needs: [test-unit]
 only:
  - master
script:
  ls TestAndDevOPS*.jar